######################################################################
# Automatically generated by qmake (3.1) Fri Jul 8 07:52:22 2022
######################################################################

TEMPLATE = app
TARGET   = cdimage
QT      += widgets concurrent
INCLUDEPATH += .

HEADERS += src/cdpreview.h \
           src/converter.h \
           src/createtrackdialog.h \
           src/mainwindow.h \
           src/discprofile.h \
           src/idiscbackend.h \
           src/icalibrationmethod.h \
           src/discdetector.h \
           src/profiledatabase.h \
           src/testpatterngenerator.h \
           src/photocalibration.h \
           src/drivereadbackcalibration.h \
           src/calibrationwizard.h

SOURCES += src/cdpreview.cpp \
           src/converter.cpp \
           src/createtrackdialog.cpp \
           src/main.cpp \
           src/mainwindow.cpp \
           src/discprofile.cpp \
           src/discdetector.cpp \
           src/profiledatabase.cpp \
           src/testpatterngenerator.cpp \
           src/photocalibration.cpp \
           src/drivereadbackcalibration.cpp \
           src/calibrationwizard.cpp

unix:HEADERS  += src/linuxdiscbackend.h
unix:SOURCES  += src/linuxdiscbackend.cpp

win32:HEADERS += src/windowsdiscbackend.h
win32:SOURCES += src/windowsdiscbackend.cpp

FORMS += src/createtrackdialog.ui \
         src/mainwindow.ui \
         src/calibrationwizard.ui

RESOURCES += resources/profiles.qrc
